---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
  :queues:
    - [ efinding_staging_report, 3 ]
    - [ efinding_staging_email, 2 ]
    - [ efinding_staging_push, 1 ]
development:
  :concurrency: 10
  :queues:
    - [ efinding_report, 3 ]
    - [ efinding_email, 2 ]
    - [ efinding_push, 1 ]
production:
  :concurrency: 10
  :queues:
    - [ efinding_report, 3 ]
    - [ efinding_email, 2 ]
    - [ efinding_push, 1 ]