---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 5
  :queues:
    - [ efinding_pitagora_report, 3 ]
    - [ efinding_pitagora_email, 2 ]
    - [ efinding_pitagora_push, 1 ]
development:
  :concurrency: 5
  :queues:
    - [ efinding_report, 3 ]
    - [ efinding_email, 2 ]
    - [ efinding_push, 1 ]
production:
  :concurrency: 5
  :queues:
    - [ efinding_report, 3 ]
    - [ efinding_email, 2 ]
    - [ efinding_push, 1 ]